//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class log11Service
{
    public System.DateTime querytime { get; set; }
    public string machine { get; set; }
    public string network { get; set; }
    public string method { get; set; }
    public string location { get; set; }
    public string variable { get; set; }
    public string starttime { get; set; }
    public string endtime { get; set; }
    public string proctime { get; set; }
    public Nullable<int> reccount { get; set; }
    public string userhost { get; set; }
}
